title: Saurabh Dugdhe
logo: /assets/img/saurabh.png

description: 
<p align="center">
<a href="/assets/pdf/resume.pdf">Resume</a> 
<a href="https://www.linkedin.com/in/saurabhdugdhe/">LinkedIn</a> |
<a href="https://github.com/saurabhdugdhe">GitHub</a>

show_downloads: true
google_analytics:

theme: jekyll-theme-minimal
